// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'show': string;
  'x-canvas-scroll': string;
  'x-canvas-scroll-end': string;
  'x-canvas-scroll-inner': string;
  'x-canvas-table': string;
  'x-canvas-table-selection-cell': string;
  'x-scroll-shadow-left': string;
  'x-scroll-shadow-right': string;
}
declare var cssExports: CssExports;
export = cssExports;
